### ISSUE TITLE
Old reddit page not working 

### ISSUE THREAD

**Issue by riyadikshit** [shivamadhau/graffiti#2]
**Describe the bug**
The phishing page of reddit old is not working 

**To Reproduce**
step 1 :- start the tool
step 2 :- select phishing page option
step 3 :- select reddit old page
step 4 :- see
It must be the reddit old page but some time it not works or it shows a totally different page

**Smartphone**
 - Device: Samsung Galaxy s24 ultra 
 - OS: Android 14
 - Browser: brave browser 
 - Version: idk

**Additional context**
I can help in solving it if you want

**Comment by shivamadhau** [comment]
Ok it's not a problem in this repository as this repository takes web source from another repository
Actually I am working on it
